### ISSUE TITLE
Geenerates error

### ISSUE THREAD

**Issue by Nilaim** [Uspizig/Ttn-gooogle-script#1]
Exception: Unexpected error while getting the method or property openById on object SpreadsheetApp. (line 2, file "Code")

**Comment by Uspizig** [comment]
did you replace the "YOURSheetdID" with your coresponding sheet ID?

**Comment by Nilaim** [comment]
Yes, in both places. I have tried with the full sheet URL, and also just the sheet name. always same error

**Comment by Uspizig** [comment]
so there is your Error: Neither the Sheet Name nor the full Sheet URL is the correct one.
Only the part in between the / in / in your URL
Sheed-ID should be something like: 15rKwlqlXLtK4hGgeRlSkMj72b5VLMT6hq7jz4v7Vr-T5

from the URL: https://docs.google.com/spreadsheets/d/15rKwlqlXLtK4hGgeRlSkMj72b5VLMT6hq7jz4v7Vr-T5/edit#gid=0

**Comment by Nilaim** [comment]
Great thanks! It is working!
